Update google_spreadsheet.py
Trying to avoid this error by putting the temp_f conversion after checking if it is None
Traceback (most recent call last):
  File "/home/pi/documents/raspi/google_spreadsheet.py", line 74, in <module>
    temp = int(temp)
TypeError: int() argument must be a string or a number, not 'NoneType'